services:
  db:
    container_name: postgres_db
    image: postgres:13-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - "5432:5432"

  db_test:
    container_name: postgres_test_db
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "testdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sleep_api:
    build: ./sleep/.
    volumes:
      - ./sleep/:/sleep/
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USER=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
